# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inverterAsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=200)),
                ('health', models.CharField(max_length=200)),
                ('activeSince', models.DateTimeField(verbose_name='date published')),
                ('temp', models.IntegerField(default=0)),
                ('prod', models.IntegerField(default=0)),
                ('switch', models.IntegerField(default=0)),
                ('uptime', models.IntegerField(default=0)),
            ],
        ),
    ]
